drivers.windows.webdriver.chrome.driver = drivers/chromedriver_win32/chromedriver.exe
drivers.mac.webdriver.chrome.driver = drivers/chromedriver_win32/chromedriver
drivers.linux.webdriver.chrome.driver = drivers/chromedriver_win32/chromedriver
webdriver.driver=chrome
#serenity.take.screenshots=FOR_FAILURES
serenity.restart.browser.for.each=NEVER
serenity.project.name=IMDB Application